# Change these first
owner: Team-Acento # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://acento.us/
  - name: App
    url: https://acento.us/app
  - name: API
    url: https://acento.us/api/v1
  - name: Developer Server
    url: https://acento.sectly1.repl.co/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Acento
  introTitle: "**Acento** Status Page."
  introMessage: See Live Status, Incidents And Scheduled Maintenance!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://acento.us/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
